import { Venue } from "./venue";
export interface Space {
    id: number;
    name: string;
    alias: string;
    credits2x: boolean;
    allowPublicSpaces: boolean;
    roundHours: number;
    customAdditionalTime: number;
    quantityRepublishCustom: number;
    notAllowCredit: boolean;
    quantityUnlimited: boolean;
    securityDeposit?: boolean;
    instantlyBookable?: boolean;
    usedQuantity: number;
    capacity: number;
    reservationCount?: number;
    price: number;
    tax: number;
    spaceTypeId: number;
    packageShow: any;
    packageShowName?: string;
    description: string;
    quantity: number;
    securityDepositPrice: number;
    hideQuantity: boolean;
    creditsHalf: boolean;
    quantityRepublish: number;
    status: string;
    updatedBy?: any;
    createdBy?: any;
    spaceType: any;
    chargeType: string;
    chargeVariant: string;
    venueId: number;
    createdById: number;
    updatedById: number;
    photos: [];
    venue: Venue;
    creditHours: [];
    eventData: any;
    amenities: string[];
    billCycleStart?: number;
    access247: boolean;
    isOngoingCheckin?: boolean;
    reservation?: [];
    packageBrands?: [];
    packageVenueTypes?: [];
    packageVenues?: [];
    packageSpaceTypes?: [];
    packageSubCategories: [] | undefined;
    uploadAttachments?: string[];
    venueIds?: number[];
    imageUrls?: string[];
    stripeData?: any;
    subCategories: [] | undefined;
}
